export enum ReturnStatus {
  RETURN_REQUESTED = 'RETURN_REQUESTED',
  RETURN_ACCEPTED = 'RETURN_ACCEPTED',
  RETURN_IN_TRANSIT='RETURN_IN_TRANSIT',
  RETURN_RECEIVED = 'RETURN_RECEIVED',
  WAITING_APPROVAL = 'WAITING_APPROVAL',
  PROCESSED = 'PROCESSED',
  COMPLETED = 'COMPLETED',
}