import { GstType } from "./gst-types.enum";

export enum State {
    ANDHRA_PRADESH = "Andhra Pradesh",
    ARUNACHAL_PRADESH = "Arunachal Pradesh",
    ASSAM = "Assam",
    BIHAR = "Bihar",
    CHHATTISGARH = "Chhattisgarh",
    GOA = "Goa",
    GUJARAT = "Gujarat",
    HARYANA = "Haryana",
    HIMACHAL_PRADESH = "Himachal Pradesh",
    JHARKHAND = "Jharkhand",
    KARNATAKA = "Karnataka",
    KERALA = "Kerala",
    MADHYA_PRADESH = "Madhya Pradesh",
    MAHARASHTRA = "Maharashtra",
    MANIPUR = "Manipur",
    MEGHALAYA = "Meghalaya",
    MIZORAM = "Mizoram",
    NAGALAND = "Nagaland",
    ODISHA = "Odisha",
    PUNJAB = "Punjab",
    RAJASTHAN = "Rajasthan",
    SIKKIM = "Sikkim",
    TAMIL_NADU = "Tamil Nadu",
    TELANGANA = "Telangana",
    TRIPURA = "Tripura",
    UTTARAKHAND = "Uttarakhand",
    UTTAR_PRADESH = "Uttar Pradesh",
    WEST_BENGAL = "West Bengal",
    ANDAMAN_NICOBAR = "Andaman and Nicobar Islands",
    CHANDIGARH = "Chandigarh",
    DADRA_NAGAR_HAVELI = "Dadra and Nagar Haveli",
    DAMAN_DIU = "Daman and Diu",
    DELHI = "Delhi",
    LAKSHADWEEP = "Lakshadweep",
    PUDUCHERRY = "Puducherry"
}

export const StateGstTypeMap: Record<State, GstType> = {
  [State.ANDHRA_PRADESH]: GstType.IGST,
  [State.ARUNACHAL_PRADESH]: GstType.IGST,
  [State.ASSAM]: GstType.IGST,
  [State.BIHAR]: GstType.IGST,
  [State.CHHATTISGARH]: GstType.IGST,
  [State.GOA]: GstType.IGST,
  [State.GUJARAT]: GstType.IGST,
  [State.HARYANA]: GstType.IGST,
  [State.HIMACHAL_PRADESH]: GstType.IGST,
  [State.JHARKHAND]: GstType.IGST,
  [State.KARNATAKA]: GstType.IGST,
  [State.KERALA]: GstType.IGST,
  [State.MADHYA_PRADESH]: GstType.IGST,
  [State.MAHARASHTRA]: GstType.IGST,
  [State.MANIPUR]: GstType.IGST,
  [State.MEGHALAYA]: GstType.IGST,
  [State.MIZORAM]: GstType.IGST,
  [State.NAGALAND]: GstType.IGST,
  [State.ODISHA]: GstType.IGST,
  [State.PUNJAB]: GstType.IGST,
  [State.RAJASTHAN]: GstType.IGST,
  [State.SIKKIM]: GstType.IGST,
  [State.TAMIL_NADU]: GstType.CGST_SGST,
  [State.TELANGANA]: GstType.IGST,
  [State.TRIPURA]: GstType.IGST,
  [State.UTTARAKHAND]: GstType.IGST,
  [State.UTTAR_PRADESH]: GstType.IGST,
  [State.WEST_BENGAL]: GstType.IGST,
  [State.ANDAMAN_NICOBAR]: GstType.IGST,
  [State.CHANDIGARH]: GstType.IGST,
  [State.DADRA_NAGAR_HAVELI]: GstType.IGST,
  [State.DAMAN_DIU]: GstType.IGST,
  [State.DELHI]: GstType.IGST,
  [State.LAKSHADWEEP]: GstType.IGST,
  [State.PUDUCHERRY]: GstType.IGST,
};