export enum StockMovementType {
  PURCHASE = 'PURCHASE',
  SALE = 'SALE',
  RETURN = 'RETURN',
  CUSTOMER_RETURN_DAMAGED = 'CUSTOMER_RETURN_DAMAGED',
  DAMAGED_AT_RECEIPT = 'DAMAGED_AT_RECEIPT',
  DAMAGED_IN_STORAGE = 'DAMAGED_IN_STORAGE',
  TRANSFER = 'TRANSFER',
}